INSERT INTO thread VALUES ('100','My First Thread', 'Instagram offered a first glimpse at what its ads will look like in a blog post Thursday. The sample ad, which you can see below.', 'http//', '0', 'Ricard', 'Comedia');
INSERT INTO thread VALUES ('101','My Second Thread', 'OMG! Im going to kill someone', 'http//', '0', 'Ricard', 'Comedia');
INSERT INTO thread VALUES ('102','This Fucking Program is awesome', 'PATATAAAAAAA!', 'http//', '0', 'Ricard', 'Comedia');
INSERT INTO thread VALUES ('103','My First Thread', 'Instagram offered a first glimpse at what its ads will look like in a blog post Thursday. The sample ad, which you can see below.', 'http//', '0', 'Ricard', 'Comedia');
INSERT INTO thread VALUES ('104','My Second Thread', 'OMG! Im going to kill someone', 'http//', '0', 'Ricard', 'Comedia');
INSERT INTO thread VALUES ('105','This Fucking Program is awesome', 'PATATAAAAAAA!', 'http//', '0', 'Ricard', 'Comedia');
INSERT INTO thread VALUES ('106','My First Thread', 'Instagram offered a first glimpse at what its ads will look like in a blog post Thursday. The sample ad, which you can see below.', 'http//', '0', 'Ricard', 'Comedia');
INSERT INTO thread VALUES ('107','My Second Thread', 'OMG! Im going to kill someone', 'http//', '0', 'Ricard', 'Comedia');
INSERT INTO thread VALUES ('108','This Fucking Program is awesome', 'PATATAAAAAAA!', 'http//', '0', 'Ricard', 'Comedia');
INSERT INTO thread VALUES ('109','My First Thread', 'Instagram offered a first glimpse at what its ads will look like in a blog post Thursday. The sample ad, which you can see below.', 'http//', '0', 'Ricard', 'Comedia');
INSERT INTO thread VALUES ('110','My Second Thread', 'OMG! Im going to kill someone', 'http//', '0', 'Ricard', 'Comedia');
INSERT INTO thread VALUES ('111','This Fucking Program is awesome', 'PATATAAAAAAA!', 'http//', '0', 'Ricard', 'Comedia');
